[package]
name = "bridge"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
# Downloaded
flutter_rust_bridge = { workspace = true }
# Workspace
hub = { workspace = true }
