targets:
  $default:
    sources:
      - $package$
      - lib/$lib$
      - messages/**
    builders:
      protoc_builder:
        options:
          # Directory which is treated as the root of all Protobuf files.
          root_dir: "messages/"
          # Include paths given to the Protobuf compiler during compilation.
          proto_paths:
            - "messages/"
          # The root directory for generated Dart output files.
          out_dir: "lib/messages"
